### PR TITLE
Proposed resolution for issue #35

### LINKED ISSUE #35: Async support for Tables
Queries on table storage do not support Async operations currently.

### PR DESCRIPTION
**Pull request by stewart-r**
Fixes #35 

I think this provides the necessary functionality.

As always, just let me know if there is something I ought to look at again.

### CODE REVIEW

**Comment by isaacabraham** [comment]
Thanks :-) This is great. Could it also be applied to the other operations such as ``Get``, ``Delete``, ``Insert`` and the Partition based variants?

**Comment by stewart-r** [comment]
I'm sure it could. Leave it with me :-)

**Comment by stewart-r** [comment]
Closing this for now (didn't intend to add that last commit to the PR!)

I'll issue another PR once all the async members are done

**Comment by isaacabraham** [comment]
OK great - thanks

**Pull request closed without merging**
