### PR TITLE
Make tests functions instead of values so they are discovered and run

### PR DESCRIPTION
**Pull request by theprash**
I fixed three tests so that they're actually run :)

### CODE REVIEW

**Comment by theprash** [comment]
Just noticed this is probably fixed in the expecto-tests branch anyway.

**Comment by isaacabraham** [comment]
Hmm. AV is red now. Do the tests pass locally?

**Comment by theprash** [comment]
Yep, all 79 passed locally for me. The ones failing here aren't actually the ones I enabled...

**Comment by isaacabraham** [comment]
Hmmmm

**Comment by isaacabraham** [comment]
@theprash aha. these are breaking since the latest Azure Storage Emulator (4.6.0.0). If you upgrade to that, you'll get the same test failures locally.

**Comment by theprash** [comment]
The newly released Azure Storage Emulator v5.1 fixes the issue for me locally.

**Pull request merged**
