### PR TITLE
WIP: Trying to update the build script

### PR DESCRIPTION
**Pull request by forki**
- [x] - merge build.fsx with latest scaffold
- [x] - update build dependencies
- [ ] - merge docs with latest scaffold

### CODE REVIEW

**Comment by isaacabraham** [comment]
Just trying to merge this PR. Testing locally, the FAKE script doesn't seem to work - needs complains about missing Octokit, and also missing functions createClient and Draft.

**Comment by forki** [comment]
Well, that's shit.

Maybe just look into last bits of paket build script. Shouldn't be too hard
to figure it out.

**Comment by isaacabraham** [comment]
OK. I guess I don't need the Octokit stuff here - I'm not using octopus at all?

**Comment by forki** [comment]
Do you want to create github releases?

**Comment by isaacabraham** [comment]
Yes

**Comment by isaacabraham** [comment]
Can't that just be done through GitHub tagging directly though?

**Comment by forki** [comment]
No. Not if you want to add release notes and files.

**Comment by isaacabraham** [comment]
oh. ok - let me get this all working with basic github + nuget integration first - can add release notes as a separate task. Suddenly the unit tests are not even building now.

**Comment by isaacabraham** [comment]
Ah. Looks like you did a Paket update across all the dependencies... this brought down latest Unquote which had breaking changes.

**Comment by forki** [comment]
Sorry.

**Comment by isaacabraham** [comment]
no probs. fixed that. got some other issues now though - type providers are such a pain!

**Pull request merged**
